"""Record the installed dependency closure, excluding unrelated local projects.
Run AFTER installing/upgrading requirements.txt and passing tests in an isolated venv.
This records this interpreter/platform's tested versions; it is not a universal resolver.
"""
from importlib.metadata import distribution
from pathlib import Path
import platform
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

ROOT=Path(__file__).resolve().parents[1]


def main():
    pending=[Requirement(line.strip()) for line in (ROOT/'requirements.txt').read_text(encoding='utf-8').splitlines()
             if line.strip() and not line.lstrip().startswith('#')]
    seen=set(); locked={}
    while pending:
        req=pending.pop()
        if req.url: raise ValueError(f'Direct URL dependency {req.name}: review/pin it explicitly')
        dist=distribution(req.name)
        if req.specifier and not req.specifier.contains(dist.version,prereleases=True):
            raise ValueError(f'Installed version conflicts with {req}: {dist.version}')
        name=canonicalize_name(dist.metadata['Name'])
        locked[name]=dist.version
        for extra in {''} | set(req.extras):
            if (name,extra) in seen: continue
            seen.add((name,extra))
            for raw in dist.requires or []:
                child=Requirement(raw)
                if child.marker is None or child.marker.evaluate({'extra':extra}):pending.append(child)
    header=('# Project dependency closure from the verified installed environment.\n'
            f'# Python {platform.python_version()} / {platform.system()} {platform.machine()}.\n'
            '# Generated by scripts/lock_dependencies.py; excludes unrelated editable projects.\n'
            '# Install: python -m pip install -r requirements.txt -c requirements.lock\n')
    text=header+'\n'.join(f'{n}=={v}' for n,v in sorted(locked.items()))+'\n'
    (ROOT/'requirements.lock').write_text(text,encoding='utf-8')
    print(f'Recorded {len(locked)} dependency versions for this platform')

if __name__=='__main__': main()
